# Generated by Django 5.2.3 on 2025-06-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('pending', '대기 중'), ('accepted', '수락됨'), ('declined', '거절됨')], default='accepted', max_length=10),
        ),
    ]
