# Generated by Django 5.2.3 on 2025-06-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friend_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
