# Generated by Django 5.2.3 on 2025-06-24 23:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friend_memo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendcode',
            unique_together={('user', 'code')},
        ),
    ]
