# Generated by Django 5.2.3 on 2025-06-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exp',
            field=models.PositiveIntegerField(default=0, verbose_name='경험치'),
        ),
    ]
