# Generated by Django 5.2.3 on 2025-06-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='number_name',
            field=models.CharField(max_length=20, verbose_name='학번(아이디)'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('number_name', 'univ_name')},
        ),
    ]
