# Generated by Django 5.2.1 on 2025-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio_user_image_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='major_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='student_id',
            new_name='number_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='school_name',
            new_name='univ_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='자기소개'),
        ),
    ]
