# Generated by Django 5.2.3 on 2025-06-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_number_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_name',
            field=models.CharField(max_length=20, verbose_name='학번'),
        ),
    ]
