# Generated by Django 5.2.3 on 2025-06-21 17:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_department_user_major_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='major_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='univ_name',
            new_name='school_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='number_name',
            new_name='student_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='자기소개'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='사용자', max_length=30, verbose_name='닉네임'),
        ),
    ]
