# Generated by Django 5.2.3 on 2025-06-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='content',
        ),
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quest_images/'),
        ),
        migrations.AddField(
            model_name='feed',
            name='image_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='location',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='memo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='feed',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='quest.quest'),
        ),
    ]
