# Generated by Django 5.2.3 on 2025-06-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedcommentreply',
            name='feed_comment',
        ),
        migrations.RemoveField(
            model_name='feedcommentreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedcommentreplylike',
            name='feed_comment_reply',
        ),
        migrations.RemoveField(
            model_name='feedcommentreplylike',
            name='user',
        ),
        migrations.DeleteModel(
            name='FeedCommentLike',
        ),
        migrations.DeleteModel(
            name='FeedCommentReply',
        ),
        migrations.DeleteModel(
            name='FeedCommentReplyLike',
        ),
    ]
