# Generated by Django 5.2.3 on 2025-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_feed_content_feed_image_feed_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
