# Generated by Django 5.2.3 on 2025-06-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_add_initial_quest_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
